language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - source setup/setup.sh

services:
  - mysql

before_script:
  - cat ~/.my.cnf
  - mysql -e 'create database myapp_test;'
  - mysql -e 'show databases;'

script:
  - nosetests -s
