language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - source setup/setup.sh

services:
  - mysql

before_script:
  - mysql -e 'show databases;'
  - mysql -e 'create database myapp_test;'

script:
  - nosetests
